Learnproject/LearnApp/urls.py
from django.urls import re_path
from LearnApp import views

#template tagging
app_name = 'LearnApp'

urlpatterns = [
    re_path(r'^first_page',views.first,name = 'first'),
    re_path(r'^relative',views.relative,name = 'relative'),
]

Learnproject/Learnproject/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import include
from LearnApp import views

urlpatterns = [
    re_path(r'^$',views.index,name = 'index'),
    #re_path(r'^$',views.filter_try,name = 'filter_try'),
    re_path(r'^basic_app/',include('LearnApp.urls')),
    path('admin/', admin.site.urls),
]

Learnproject/LearnApp/models.py
from django.db import models

# Create your models here.

Learnproject/LearnApp/views.py
from django.shortcuts import render


# Create your views here.
def index(call):
    my_dict = {
        'intro':'Hello World','data':14265
    }

    return render(call,'basic_app/index.html',my_dict)

def first(call):
    return render(call,'basic_app/first_page.html')

def relative(call):
    return render(call,'basic_app/relative_url_template.html')

Learnproject/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <style>
      hr{
        border-top: 1px solid red;
      }
    </style>
    <meta charset="utf-8">
    <title>Bars</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>

    <nav class = "navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class = "nav navbar-nav">
          <li> <a class="navbar-brand" href="{% url 'index' %}">Index</a> </li>
          <li> <a class="navbar-link" href="{% url 'LearnApp:first' %}">First_Page</a> </li>
          <li> <a class="navbar-link" href="{% url 'admin:index' %}">Django Admin</a> </li>
        </ul>

      </div>
    </nav>
    <hr class="my-4 solid" >
    <div class="container">

      {% block body_block %}
      <!-- Anything in this part gonna print so upper is header and below part is yout footer-->
      {% endblock %}

    </div>
</hr>

  </body>
</html>

<!-- this file is for reuse parts for every pages to indluded in base file like header.php and footer.php

Learnproject/templates/basic_app/first_page.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

<!--<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>First_Page</title>
  </head>
  <body>-->
  {% block body_block %}
    <h1>Hello First Page</h1>
    <a href="{% url 'LearnApp:relative' %}">Relative PAge</a>
  {% endblock %}
<!--  </body>
</html>
-->

Learnproject/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load static %}
{% load my_extras %}


<!--<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>-->
  {% block body_block %}
    <h1>Welcome to Index Page</h1>
    <h1>{{ intro }}</h1>
    <h1>{{ data }}</h1>
    <h1>Sum of uper number : {{ data|AddOn }}</h1>
    <a href="{% url 'LearnApp:first' %}">First_Page</a>
  {% endblock %}
<!--  </body>
</html>-->

Learnproject/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
{% extends "basic_app/base.html"  %}
<!--<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>-->
  {% block body_block %}
    <h1>Welcome to Relative Page</h1>
    <a href="{% url 'LearnApp:first' %}">first_page</a>
    <a href="{% url 'admin:index' %}">django database index</a>
    <a href="{% url 'index' %}">main index</a>
  {% endblock %}
<!--  </body>
</html>-->